<?php
$wp_ulike_string = array(
    "4"  => __('WP ULike - Most Liked Activities', 'alimir'),
    "5"  => __( 'This widget allows you to show most liked activities.', 'alimir' ),
    "6"  => __('Most Liked Activities', 'alimir'),
    "7"  => __('Users Login Text', 'alimir'),
    "8"  => __('Allow To Like', 'alimir'),
    "9"  => __('Guests Only', 'alimir'),
    "10" => __('Registered Users Only', 'alimir'),
    "11" => __('Registered Users And Guests', 'alimir'),
    "12" => __('Who Is Allowed To Like?', 'alimir'),
    "13" => __('Filter Options:', 'alimir'),
    "14" => __('Sort Options:', 'alimir'),
    "21" => __('Themes', 'alimir'),
    "22" => __('Dislike', 'alimir'),
    "23" => __('Dislike Support', 'alimir'),
    "24" => __('Text After Dislike', 'alimir'),
    "25" => __('Show Counter', 'alimir'),
    "26" => __('Show tooltips', 'alimir'),
    "30" => __('Alignment', 'alimir'),
    "31" => __('Left', 'alimir'),
    "32" => __('Center', 'alimir'),
    "33" => __('Right', 'alimir'),
    "35" => __('Cookie Life time', 'alimir'),
    "36" => __('BuddyPress Notifications', 'alimir')
);